/*
 * generated by Xtext 2.33.0
 */
package reva;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RevaDslStandaloneSetup extends RevaDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RevaDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
